service: good-friend-cron

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sendEventReminder:
    name: sendEventReminder
    description: Lambda function to send out event reminds to customers
    handler: handler.sendEventReminder
    role: sendEventReminderRole
    events:
      - schedule:
          rate: cron(0 9 * * ? *)
resources:
  Resources:
    sendEventReminderRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: sendEventReminderRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: sendEventReminderPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                  Resource:
                    - "*"
